scrape_configs:
- job_name: kafka
  scrape_interval: 5s
  static_configs:
  - targets:
    - kafka:9092
- job_name: zookeeper
  scrape_interval: 5s
  static_configs:
  - targets:
    - zookeeper:2181
- job_name: postres
  scrape_interval: 5s
  static_configs:
  - targets:
    - postgres:5432   
- job_name: message-service
  scrape_interval: 5s  
  static_configs:
  - targets:
    - message-service:7070