version: '3.2'
services:
  zookeeper:
    container_name: zookeeperDev
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    ulimits:
      memlock:
        soft: -1
        hard: -1
networks:
  default:
    external:
      name: go_app_stack