version: '3.2'
services:
  zookeeper:
    container_name: zookeeperDev
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
    ulimits:
      memlock:
        soft: -1
        hard: -1
networks:
  default:
    external:
      name: go_app_stack