version: '3.2'
services:
  kafka:
    container_name: kafkaDev
    hostname: kafka
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ulimits:
      memlock:
        soft: -1
        hard: -1
networks:
  default:
    external:
      name: go_app_stack