# run with command docker-compose -f kafka-topic-creator.yml run --rm kafka_creator
version: '3.2'
services:
  kafka_creator:
    container_name: kafka_creator
    image: confluentinc/cp-kafka:latest
    command: > 
      bash -c 'kafka-topics --create --if-not-exists --zookeeper zookeeper:22181 --partitions 1 --replication-factor 1 --topic message-topic' 
networks:
  default:
    external:
      name: go_app_stack